version: "3.8"
services:
  app:
    build: ./container/php
    volumes:
      - ./laravel:/laravel
  web:
    image: nginx:1.18-alpine
    ports:
      - 8080:80
    volumes:
      - ./laravel:/laravel
      - ./container/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /laravel
  db:
    build: ./container/mysql
    ports:
      - 33060:3306
    volumes:
      - db-store:/var/lib/mysql
volumes:
  db-store:
