version: "3.8"

volumes:
  db-store:
  laravel-sync:
    external: true

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - laravel-sync:/${PROJECT_DIR:-laravel}
      - ./conf/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_NAME:-laravel}
      DB_USERNAME: ${DB_USERNAME:-username}
      DB_PASSWORD: ${DB_PASSWORD:-userpass}
    working_dir: /${PROJECT_DIR:-laravel}

  web:
    image: nginx:1.18-alpine
    ports:
      - ${WEB_PORT:-8080}:80
    volumes:
      - .laravel-sync:/${PROJECT_DIR:-laravel}
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      DOCUMENT_ROOT: /${PROJECT_DIR:-laravel}/public
    working_dir: /${PROJECT_DIR:-laravel}

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
      args:
        TIME_ZONE: ${TIME_ZONE:-Asia/Tokyo}
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - db-store:/var/lib/mysql
      - ./conf/mysql.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_DATABASE: ${DB_NAME:-laravel}
      MYSQL_USER: ${DB_USERNAME:-username}
      MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpass}
