version: "3.8"
services:
  app:
    build: ./lib/php
    volumes:
      - ./project:/work
  web:
    image: nginx:1.18-alpine
    ports:
      - 8080:80
    volumes:
      - ./project:/work
      - ./lib/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work
  db:
    build: ./lib/mysql
    ports:
      - 33060:3306
    volumes:
      - db-store:/var/lib/mysql
volumes:
  db-store:
